name: My pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
          - name: clonar repo
            uses: actions/checkout@v2
          - name: ver conten repo
            run: ls -la
          - name: build and up docker
            run: docker compose -f docker-compose.yml up -d  --build
          - name: wait for db
            run: |
              until docker exec -it postgres pg_isready -U postgres; do
                echo "Waiting for bd to be ready to go"
                sleep 2
              done
          - name: see containers running
            run: docker ps
          - name: test
            run: curl http://localhost:5000
            