name: My pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
          - name: clonar repo
            uses: actions/checkout@v3
          - name: ver conten repo
            run: ls -la
          - name: build and up docker
            run: docker compose -f docker-compose.yml up -d  --build
          - name: wait for db
            run: |
              until docker exec mydb pg_isready -U postgres; do
                echo "Waiting for bd to be ready to go and i am bryan"
                sleep 2
              done
          - name: see containers running
            run: docker ps
          - name: wait backend
            run: sleep 20
          - name: test
            run: curl --retry 5 --retry-delay 3 http://localhost:5000
          - name: test with pytest
            run: docker exec myback pytest -v
          - name: login dockerhub
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          - name: build docker image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_app-backend:latest ./backend
          - name: push doocker image
            run: docker push ${{ secrets.DOCKER_USERNAME}}/docker_app-backend:latest
            