name: My pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
          - name: clonar repo
            uses: actions/checkout@v3
          - name: ver conten repo
            run: ls -la
          - name: build and up docker
            run: docker compose -f docker-compose.yml up -d  --build
          - name: wait for db
            run: |
              until docker exec mydb pg_isready -U postgres; do
                echo "Waiting for bd to be ready to go and i am bryan"
                sleep 2
              done
          - name: see containers running
            run: docker ps
          - name: wait backend
            run: sleep 20
          - name: test
            run: curl --retry 5 --retry-delay 3 http://localhost:5000
          - name: test with pytest
            run: docker exec myback pytest -v
  build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: clonar repo
          uses: actions/checkout@v3
        - name: login dockerhub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        - name: build docker image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker_app-backend:${{ github.sha }} ./backend
        - name: save image
          run: docker save ${{secrets.DOCKER_USERNAME }}/docker_app-backend:${{ github.sha}} -o backend_image.tar
        - name: upload image
          uses: actions/upload-artifact@v4
          with:
            name: backend_image
            path: backend_image.tar
  push:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: download image
          uses: actions/download-artifact@v4
          with:
            name: backend_image
        - name: load the image
          run: docker load -i backend_image.tar
        - name: log in
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
        
        
        - name: push docker image
          run: docker push ${{ secrets.DOCKER_USERNAME}}/docker_app-backend:${{ github.sha }}
            